version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
  build:
    commands:
      - ./gradlew javadoc jacocoTestReport build
artifacts:
  files:
    - '**/build/reports/**/*'
    - '**/build/docs/**/*'
cache:
  paths:
    - '~/.gradle/**/*'
